services:
  # --- BASE DE DATOS (Interna de Docker) ---
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Tu Workbench se conecta por el 3307 ahora
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 5s
      retries: 10

  # --- EUREKA SERVER ---
  eureka-server:
    build: ./eureka_server
    container_name: eureka-server
    ports:
      - "8761:8761"

  # --- MICROSERVICIO USUARIOS ---
  service-users:
    build: ./service_users
    container_name: service-users
    depends_on:
      db-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      # IMPORTANTE: El parámetro createDatabaseIfNotExist=true soluciona tu error
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/db_users?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # --- MICROSERVICIO TAREAS ---
  service-tasks:
    build: ./service_tasks
    container_name: service-tasks
    depends_on:
      db-mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/db_tasks?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # --- API GATEWAY ---
  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/