server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:  # 👈 NUEVA ESTRUCTURA
          routes:
            # RUTA para el microservicio de USUARIOS
            - id: service-users-route
              uri: lb://service-users
              predicates:
                - Path=/usuarios/**
              filters:
                - StripPrefix=1
                - JwtValidationFilter

            # RUTA para el microservicio de TAREAS
            - id: service-tasks-route
              uri: lb://service-tasks
              predicates:
                - Path=/tareas/**
              filters:
                - StripPrefix=1
                - JwtValidationFilter

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true